spring:
  datasource:
    url: jdbc:oracle:thin:@10.8.0.61:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: IDOCITAS
    password: idocitas123
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 30000
      pool-name: HikariPoolBooks
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect